### ISSUE TITLE
Problem accented characters in French and other European languages

### ISSUE THREAD

**Issue by netsubway** [Skarlso/SublimeGmailPlugin#1]
Hello and thank you for this wonderful plugin.
I tested it and everything is fine, except when there are special characters with emphasis in the text (like é,è,à,ç,ù, etc..)  I have the message "The message was not sent etc ..."
To solve this I added around line 27 instead of :
server.sendmail(FROM, TO, message)
this line:
server.sendmail(FROM, TO, message.encode('utf8'))

Now everything is ok and messages can be sent

**Comment by Skarlso** [comment]
Awesome dude. I'll include the fix. :-)

**Comment by Skarlso** [comment]
Done. :)
